import crypto from "node:crypto";
import { EventType } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/server/db";
import { recalculateDates } from "@/server/attendance-service";

const schema = z.object({ deviceId: z.string(), events: z.array(z.object({ externalId: z.string().min(1), timestamp: z.coerce.date(), type: z.nativeEnum(EventType) })).min(1).max(10000) });
export async function POST(request: Request) { const token = request.headers.get("authorization")?.replace(/^Bearer\s+/i, "") || ""; if (!process.env.CRON_SECRET || token !== process.env.CRON_SECRET) return NextResponse.json({ error: { code: "UNAUTHORIZED", message: "Invalid scheduler credentials." } }, { status: 401 }); const parsed = schema.safeParse(await request.json().catch(() => ({}))); if (!parsed.success) return NextResponse.json({ error: { code: "VALIDATION_ERROR", message: "Invalid scheduled import payload." } }, { status: 400 }); const device = await db.attendanceDevice.findUnique({ where: { id: parsed.data.deviceId } }); if (!device || !device.active) return NextResponse.json({ error: { code: "NOT_FOUND", message: "Active device not found." } }, { status: 404 }); let imported = 0; let duplicates = 0; const affected = new Map<string, Date>(); for (const event of parsed.data.events) { const employee = await db.employee.findFirst({ where: { companyId: device.companyId, OR: [{ employeeCode: event.externalId }, { deviceMappings: { some: { deviceId: device.id, externalId: event.externalId } } }] }, select: { id: true } }); const fingerprint = crypto.createHash("sha256").update([device.id, event.externalId, event.timestamp.toISOString(), event.type].join("|")).digest("hex"); try { await db.rawAttendanceEvent.create({ data: { companyId: device.companyId, deviceId: device.id, employeeId: employee?.id, externalId: event.externalId, timestamp: event.timestamp, type: event.type, fingerprint } }); imported++; if (employee) affected.set(employee.id, event.timestamp); } catch { duplicates++; } } const dates = Array.from(new Map(Array.from(affected.values()).map((date) => { const day = new Date(date); day.setUTCHours(0, 0, 0, 0); return [day.toISOString(), day]; })).values()); await recalculateDates(device.companyId, Array.from(affected.keys()), dates); return NextResponse.json({ data: { imported, duplicates, affectedEmployees: affected.size } }); }
