import crypto from "node:crypto";
import * as XLSX from "xlsx";
import { EventType } from "@prisma/client";

export type ParsedRow = { externalId: string; timestamp: Date; type: EventType; sourceRow: number; raw: Record<string, unknown> };
export function parseDateTime(value: unknown) { const date = new Date(String(value).trim().replace("/","-")); return Number.isNaN(date.getTime()) ? null : date; }
export function normalizeType(value: unknown): EventType { const v = String(value ?? "").trim().toLowerCase(); if (["in","entry","ورود","1"].includes(v)) return EventType.IN; if (["out","exit","خروج","0"].includes(v)) return EventType.OUT; if (["break_start","شروع استراحت"].includes(v)) return EventType.BREAK_START; if (["break_end","پایان استراحت"].includes(v)) return EventType.BREAK_END; return EventType.UNKNOWN; }
function rowsFromMatrix(rows: Record<string, unknown>[], mapping: { externalId: string; timestamp: string; type?: string }) { return rows.map((row,index) => { const timestamp = parseDateTime(row[mapping.timestamp]); const externalId = String(row[mapping.externalId] ?? "").trim(); return timestamp && externalId ? { externalId, timestamp, type: normalizeType(mapping.type ? row[mapping.type] : undefined), sourceRow: index+2, raw: row } : null; }).filter((row): row is ParsedRow => Boolean(row)); }
export function parseDelimited(content: string, mapping: { externalId: string; timestamp: string; type?: string }) { const lines = content.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean); if (!lines.length) return []; const headers = lines[0].split(",").map((h) => h.trim()); const rows = lines.slice(1).map((line) => { const values = line.split(","); return Object.fromEntries(headers.map((h,i) => [h, values[i]?.trim() ?? ""])); }); return rowsFromMatrix(rows, mapping); }
export function parseXlsx(buffer: Buffer, mapping: { externalId: string; timestamp: string; type?: string }, sheet?: string) { const workbook = XLSX.read(buffer, { type: "buffer", cellDates: true, cellFormula: false }); const name = sheet ?? workbook.SheetNames[0]; if (!name) return []; const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(workbook.Sheets[name], { defval: "" }); return rowsFromMatrix(rows,mapping); }
export function fingerprint(deviceId: string, row: ParsedRow) { return crypto.createHash("sha256").update([deviceId,row.externalId,row.timestamp.toISOString(),row.type].join("|")).digest("hex"); }
