"use client";

import { useEffect, useState } from "react";

type Line = { id: string; label: string; amount: string; type: string; sourceData?: unknown };
type AttendanceSummary = { workedDays?: number; absenceDays?: number; leaveDays?: number; overtimeMinutes?: number; lateMinutes?: number; earlyDepartureMinutes?: number };
type Run = { id: string; grossAmount: string; taxableAmount: string; insurableAmount: string; employerInsurance: string; totalDeductions: string; netPayable: string; publishedAt: string | null; acknowledgedAt: string | null; snapshot?: { attendanceSummary?: AttendanceSummary }; period: { year: number; month: number; status: string }; lines: Line[]; payment?: { status: string; paidAt: string | null; paymentReference: string | null } | null };

export default function PayslipsPage() {
  const [runs, setRuns] = useState<Run[]>([]);
  const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/v1/payroll/runs"); const result = await response.json(); setRuns(result.data || []); }
  useEffect(() => { void load(); }, []);
  async function acknowledge(id: string) { const response = await fetch(`/api/v1/payroll/runs/${id}/acknowledge`, { method: "POST" }); if (response.ok) { setMessage("Payslip acknowledgement recorded."); void load(); } }
  return <><div className="sectionTitle"><div><p className="eyebrow">Payroll transparency</p><h1>My payslips</h1><p>Each payslip shows the same finalized amounts used for payment and reporting.</p></div></div>{message && <div className="alert success">{message}</div>}{runs.length ? runs.map((run) => { const attendance = run.snapshot?.attendanceSummary; return <section className="card" key={run.id}><div className="sectionTitle"><div><h2>{run.period.year}/{String(run.period.month).padStart(2, "0")}</h2><p className="muted">Status: {run.period.status} · {run.publishedAt ? "Published" : "Not published"} · Payment: {run.payment?.status ?? "PENDING"}{run.payment?.paidAt ? ` · Paid ${new Date(run.payment.paidAt).toLocaleDateString()}` : ""}</p></div><div>{run.publishedAt && <button className="button secondary" onClick={() => window.open(`/api/v1/payroll/runs/${run.id}/print`, "_blank", "noopener,noreferrer")}>Print / save PDF</button>}{run.publishedAt && !run.acknowledgedAt && <button className="button primary" onClick={() => void acknowledge(run.id)}>Acknowledge</button>}</div></div>{attendance && <div className="two" style={{ marginBottom: 18 }}><div className="card"><strong>Attendance basis</strong><p className="muted">Worked days: {attendance.workedDays ?? 0} · Leave days: {attendance.leaveDays ?? 0} · Absence days: {attendance.absenceDays ?? 0}</p><p className="muted">Overtime: {attendance.overtimeMinutes ?? 0} min · Late: {attendance.lateMinutes ?? 0} min · Early departure: {attendance.earlyDepartureMinutes ?? 0} min</p></div><div className="card"><strong>Calculation bases</strong><p className="muted">Taxable: {Number(run.taxableAmount).toLocaleString()} ریال · Insurable: {Number(run.insurableAmount).toLocaleString()} ریال</p><p className="muted">Employer insurance cost: {Number(run.employerInsurance).toLocaleString()} ریال (not deducted from employee pay)</p></div></div>}<div className="tableWrap"><table><thead><tr><th>Item</th><th>Amount</th><th>Formula/source</th></tr></thead><tbody>{run.lines.map((line) => <tr key={line.id}><td>{line.label}<br /><small className="muted">{line.type}</small></td><td>{Number(line.amount).toLocaleString()} ریال</td><td>{line.sourceData ? <details><summary>Show basis</summary><code>{JSON.stringify(line.sourceData)}</code></details> : "—"}</td></tr>)}<tr><th>Gross compensation</th><th>{Number(run.grossAmount).toLocaleString()} ریال</th><th /></tr><tr><th>Total deductions</th><th>{Number(run.totalDeductions).toLocaleString()} ریال</th><th /></tr><tr><th>Net payable</th><th>{Number(run.netPayable).toLocaleString()} ریال</th><th /></tr></tbody></table></div></section>; }) : <div className="card empty">No published payslips are available.</div>}</>;
}
