"use client";
import { useEffect, useState } from "react";

type Employee = { id: string; employeeCode: string; firstName: string; lastName: string };
type Compensation = { id: string; status: string; baseSalary: string; effectiveFrom: string; effectiveTo?: string | null; employee: Employee };
type Period = { id: string; year: number; month: number; status: string; _count: { runs: number }; ruleSet: { name: string; version: number } };
type RuleSet = { id: string; name: string; calendarYear: number; version: number; status: string; effectiveFrom: string };
type PayrollPolicy = { id: string; name: string; version: number; status: string };

export default function PayrollPage() {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [compensation, setCompensation] = useState<Compensation[]>([]);
  const [periods, setPeriods] = useState<Period[]>([]);
  const [rules, setRules] = useState<RuleSet[]>([]);
  const [policies, setPolicies] = useState<PayrollPolicy[]>([]);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  async function load() {
    const [employeeResult, compensationResult, periodsResult, rulesResult, policiesResult] = await Promise.all([fetch("/api/v1/employees"), fetch("/api/v1/payroll/compensation"), fetch("/api/v1/payroll/periods"), fetch("/api/v1/payroll/rules"), fetch("/api/v1/payroll/policies")]);
    const [employeeJson, compensationJson, periodsJson, rulesJson, policiesJson] = await Promise.all([employeeResult.json(), compensationResult.json(), periodsResult.json(), rulesResult.json(), policiesResult.json()]);
    setEmployees(employeeJson.data || []); setCompensation(compensationJson.data || []); setPeriods(periodsJson.data || []); setRules(rulesJson.data || []); setPolicies(policiesJson.data || []);
  }
  useEffect(() => { void load(); }, []);
  async function createCompensation(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setMessage(""); setError("");
    const form = new FormData(event.currentTarget); const input = Object.fromEntries(form);
    const response = await fetch("/api/v1/payroll/compensation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employeeId: input.employeeId, baseSalary: Number(input.baseSalary), effectiveFrom: input.effectiveFrom, contractType: input.contractType, jobTitle: input.jobTitle || null, payrollIdentifier: input.payrollIdentifier || null, status: "ACTIVE", components: [] }) });
    const result = await response.json(); if (!response.ok) { setError(result.error?.message || "Could not save compensation."); return; } setMessage("Compensation profile saved with an audit trail."); event.currentTarget.reset(); void load();
  }
  async function calculate(id: string) { setMessage(""); setError(""); const response = await fetch(`/api/v1/payroll/periods/${id}/calculate`, { method: "POST" }); const result = await response.json(); if (!response.ok) setError(result.error?.message || "Calculation failed."); else { setMessage(`${result.data.count} payroll records calculated.`); void load(); } }
  async function transition(id: string, status: string) { setMessage(""); setError(""); const response = await fetch(`/api/v1/payroll/periods/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const result = await response.json(); if (!response.ok) setError(result.error?.message || "Could not change payroll status."); else { setMessage(`Payroll status changed to ${status}.`); void load(); } }
  async function createRules(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const input = Object.fromEntries(form); let rulesValue: unknown; try { rulesValue = JSON.parse(String(input.rules)); } catch { setError("Legal rules must be valid JSON."); return; } const response = await fetch("/api/v1/payroll/rules", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: input.name, calendarYear: Number(input.calendarYear), version: Number(input.version), effectiveFrom: input.effectiveFrom, sourceReference: input.sourceReference || null, rules: rulesValue }) }); const result = await response.json(); if (!response.ok) { setError(result.error?.message || "Could not save rule set."); return; } setMessage("Draft legal rule set saved. It must be approved before payroll can use it."); event.currentTarget.reset(); void load(); }
  async function createPeriod(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const input = Object.fromEntries(form); const response = await fetch("/api/v1/payroll/periods", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ year: Number(input.year), month: Number(input.month), startDate: input.startDate, endDate: input.endDate, ruleSetId: input.ruleSetId, payrollPolicyId: input.payrollPolicyId || null }) }); const result = await response.json(); if (!response.ok) { setError(result.error?.message || "Could not create payroll period."); return; } setMessage("Payroll period created."); event.currentTarget.reset(); void load(); }
  async function createPolicy(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const input = Object.fromEntries(form); let settings: unknown; try { settings = JSON.parse(String(input.settings)); } catch { setError("Company policy must be valid JSON."); return; } const response = await fetch("/api/v1/payroll/policies", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: input.name, version: Number(input.version), effectiveFrom: input.effectiveFrom, settings }) }); const result = await response.json(); if (!response.ok) { setError(result.error?.message || "Could not save company policy."); return; } setMessage("Draft company policy saved."); event.currentTarget.reset(); void load(); }
  return <><div className="sectionTitle"><div><p className="eyebrow">Compensation and payment control</p><h1>Payroll</h1><p>One source of truth from actual compensation through calculation and payment.</p></div></div>
    {(message || error) && <div className={`alert ${error ? "error" : "success"}`}>{error || message}</div>}
    <section className="card"><h2>Record employee compensation</h2><p className="muted">Amounts are stored as the employee&apos;s actual compensation. No shadow salary is created.</p><form className="stack" onSubmit={createCompensation}><label>Employee<select name="employeeId" required>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.employeeCode} · {employee.firstName} {employee.lastName}</option>)}</select></label><div className="two"><label>Base salary (ریال)<input name="baseSalary" type="number" min="0" step="1" required /></label><label>Effective from<input name="effectiveFrom" type="date" required /></label></div><div className="two"><label>Contract type<input name="contractType" defaultValue="STANDARD" required /></label><label>Payroll identifier<input name="payrollIdentifier" /></label></div><label>Job title<input name="jobTitle" /></label><button className="button primary">Save compensation</button></form></section>
    <section className="card"><h2>Compensation history</h2>{compensation.length ? <div className="tableWrap"><table><thead><tr><th>Employee</th><th>Status</th><th>Base salary</th><th>Effective from</th></tr></thead><tbody>{compensation.map((row) => <tr key={row.id}><td>{row.employee.employeeCode} · {row.employee.firstName} {row.employee.lastName}</td><td>{row.status}</td><td>{Number(row.baseSalary).toLocaleString()}</td><td>{new Date(row.effectiveFrom).toLocaleDateString()}</td></tr>)}</tbody></table></div> : <div className="empty">No compensation profiles recorded.</div>}</section>
    <section className="card"><h2>Versioned legal rules</h2><p className="muted">Rule sets are stored with a checksum and source reference. The calculation engine never silently invents missing legal values.</p><form className="stack" onSubmit={createRules}><div className="two"><label>Name<input name="name" placeholder="Iran payroll rules" required /></label><label>Source reference<input name="sourceReference" placeholder="Official circular or legal reference" /></label></div><div className="two"><label>Persian year<input name="calendarYear" type="number" min="1300" required /></label><label>Version<input name="version" type="number" min="1" defaultValue="1" required /></label></div><label>Effective from<input name="effectiveFrom" type="date" required /></label><label>Rules JSON<textarea name="rules" defaultValue={'{"workingDays":30,"workingHoursPerDay":7.3333,"overtimeMultiplier":1.4,"employeeInsuranceRate":0,"employerInsuranceRate":0,"taxRate":0}'} required /></label><button className="button secondary">Save draft rule set</button></form>{rules.length > 0 && <div className="tableWrap"><table><thead><tr><th>Rule set</th><th>Year/version</th><th>Status</th><th>Action</th></tr></thead><tbody>{rules.map((rule) => <tr key={rule.id}><td>{rule.name}</td><td>{rule.calendarYear} / {rule.version}</td><td>{rule.status}</td><td>{rule.status === "DRAFT" && <button className="button secondary" onClick={() => void fetch(`/api/v1/payroll/rules/${rule.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "APPROVED" }) }).then(() => load())}>Approve</button>}</td></tr>)}</tbody></table></div>}</section>
    <section className="card"><h2>Create payroll period</h2><form className="stack" onSubmit={createPeriod}><div className="two"><label>Persian year<input name="year" type="number" min="1300" required /></label><label>Month<input name="month" type="number" min="1" max="12" required /></label></div><div className="two"><label>Start date<input name="startDate" type="date" required /></label><label>End date<input name="endDate" type="date" required /></label></div><label>Approved rule set<select name="ruleSetId" required><option value="">Select a rule set</option>{rules.filter((rule) => rule.status === "APPROVED").map((rule) => <option key={rule.id} value={rule.id}>{rule.calendarYear} · {rule.name} v{rule.version}</option>)}</select></label><label>Active company policy<select name="payrollPolicyId"><option value="">No policy selected</option>{policies.filter((policy) => policy.status === "ACTIVE").map((policy) => <option key={policy.id} value={policy.id}>{policy.name} v{policy.version}</option>)}</select></label><button className="button secondary">Create period</button></form></section>
    <section className="card"><h2>Company payment policy</h2><p className="muted">Policy records contain company choices only; they cannot replace legal rules or alter the actual paid amount.</p><form className="stack" onSubmit={createPolicy}><div className="two"><label>Name<input name="name" placeholder="Standard company policy" required /></label><label>Version<input name="version" type="number" min="1" defaultValue="1" required /></label></div><label>Effective from<input name="effectiveFrom" type="date" required /></label><label>Policy JSON<textarea name="settings" defaultValue={'{"rounding":"nearest-rial","graceMinutes":0,"overtimeRequiresApproval":true}'} required /></label><button className="button secondary">Save draft policy</button></form>{policies.length > 0 && <div className="tableWrap"><table><thead><tr><th>Policy</th><th>Version</th><th>Status</th><th /></tr></thead><tbody>{policies.map((policy) => <tr key={policy.id}><td>{policy.name}</td><td>{policy.version}</td><td>{policy.status}</td><td>{policy.status === "DRAFT" && <button className="button secondary" onClick={() => void fetch(`/api/v1/payroll/policies/${policy.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "ACTIVE" }) }).then(() => load())}>Activate</button>}</td></tr>)}</tbody></table></div>}</section>
    <section className="card"><h2>Payroll periods</h2><p className="muted">The creator cannot approve a payroll period. Submit calculated payroll for review, then a second payroll administrator must approve it.</p>{periods.length ? <div className="tableWrap"><table><thead><tr><th>Period</th><th>Status</th><th>Rule set</th><th>Employees</th><th /></tr></thead><tbody>{periods.map((period) => <tr key={period.id}><td>{period.year}/{String(period.month).padStart(2, "0")}</td><td>{period.status}</td><td>{period.ruleSet.name} v{period.ruleSet.version}</td><td>{period._count.runs}</td><td>{["DRAFT", "CALCULATED", "CORRECTED"].includes(period.status) && <button className="button secondary" onClick={() => void calculate(period.id)}>Calculate</button>}{period.status === "CALCULATED" && <button className="button secondary" onClick={() => void transition(period.id, "IN_REVIEW")}>Submit for review</button>}{period.status === "IN_REVIEW" && <button className="button primary" onClick={() => void transition(period.id, "APPROVED")}>Approve</button>}{["APPROVED", "PAID", "LOCKED"].includes(period.status) && <button className="button secondary" onClick={() => void fetch(`/api/v1/payroll/periods/${period.id}/publish`, { method: "POST" }).then(() => load())}>Publish payslips</button>}</td></tr>)}</tbody></table></div> : <div className="empty">No payroll periods created.</div>}</section>
  </>;
}
