import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/server/auth";
import { db } from "@/server/db";
import { canReadAll } from "@/server/permissions";
import { audit } from "@/server/audit"; import { recalculateAttendanceDay } from "@/server/attendance-service";
const schema=z.object({id:z.string(),type:z.enum(["leave","offtime","correction"]),approved:z.boolean(),comment:z.string().optional()});
export async function GET(){const user=await getCurrentUser();if(!user||!["ADMIN","HR_ADMIN","MANAGER"].includes(user.role))return NextResponse.json({error:{code:"FORBIDDEN",message:"دسترسی کافی ندارید."}},{status:403});const scope=canReadAll(user)?{companyId:user.companyId}:{companyId:user.companyId,employee:{teamId:{in:(await db.managerAssignment.findMany({where:{managerId:user.id},select:{teamId:true}})).map(x=>x.teamId)}}};const [leave,offtime,correction]=await Promise.all([db.leaveRequest.findMany({where:{...scope,status:{in:["PENDING_MANAGER","PENDING_ADMIN","SUBMITTED"]}},include:{employee:true,leaveType:true},orderBy:{createdAt:"asc"}}),db.offTimeRequest.findMany({where:{...scope,status:{in:["PENDING_MANAGER","PENDING_ADMIN","SUBMITTED"]}},include:{employee:true},orderBy:{createdAt:"asc"}}),db.attendanceCorrectionRequest.findMany({where:{...scope,status:{in:["PENDING_MANAGER","PENDING_ADMIN","SUBMITTED"]}},include:{employee:true},orderBy:{createdAt:"asc"}})]);return NextResponse.json({data:{leave,offtime,correction}});}
export async function POST(request:Request){const user=await getCurrentUser();if(!user||!["ADMIN","HR_ADMIN","MANAGER"].includes(user.role))return NextResponse.json({error:{code:"FORBIDDEN",message:"دسترسی کافی ندارید."}},{status:403});const body=schema.safeParse(await request.json());if(!body.success)return NextResponse.json({error:{code:"VALIDATION_ERROR",message:"تصمیم معتبر نیست."}},{status:400});const input=body.data;const model=input.type==="leave"?"leaveRequest":input.type==="offtime"?"offTimeRequest":"attendanceCorrectionRequest";const current=await (model==="leaveRequest"?db.leaveRequest.findFirst({where:{id:input.id,companyId:user.companyId}}):model==="offTimeRequest"?db.offTimeRequest.findFirst({where:{id:input.id,companyId:user.companyId}}):db.attendanceCorrectionRequest.findFirst({where:{id:input.id,companyId:user.companyId}}));if(!current||["APPROVED","REJECTED","CANCELLED"].includes(current.status))return NextResponse.json({error:{code:"CONFLICT",message:"این درخواست قبلاً تعیین تکلیف شده است."}},{status:409});if(current.employeeId===user.employee?.id)return NextResponse.json({error:{code:"FORBIDDEN",message:"ثبت تصمیم برای درخواست خودتان مجاز نیست."}},{status:403});const employee=await db.employee.findUnique({where:{id:current.employeeId}});if(user.role==="MANAGER"&&(!employee?.teamId||!(await db.managerAssignment.findFirst({where:{managerId:user.id,teamId:employee.teamId}})))&&!canReadAll(user))return NextResponse.json({error:{code:"FORBIDDEN",message:"درخواست خارج از حوزهٔ شماست."}},{status:403});const status=input.approved?"APPROVED":"REJECTED";await db.$transaction(async(tx)=>{if(model==="leaveRequest")await tx.leaveRequest.update({where:{id:input.id},data:{status}});if(model==="offTimeRequest")await tx.offTimeRequest.update({where:{id:input.id},data:{status}});if(model==="attendanceCorrectionRequest")await tx.attendanceCorrectionRequest.update({where:{id:input.id},data:{status}});const target=await tx.user.findFirst({where:{companyId:user.companyId,employee:{id:current.employeeId}}});if(target)await tx.notification.create({data:{companyId:user.companyId,userId:target.id,employeeId:current.employeeId,title:input.approved?"درخواست تأیید شد":"درخواست رد شد",body:input.comment||"تصمیم درخواست شما ثبت شد.",href:"/requests"}});});const requestDate=model==="leaveRequest"?(current as any).startDate:(current as any).date;await recalculateAttendanceDay(user.companyId,current.employeeId,requestDate);await audit({companyId:user.companyId,actorId:user.id,action:input.approved?"request.approve":"request.reject",entityType:model,entityId:input.id,after:{comment:input.comment}});return NextResponse.json({data:{status}});}
