"use client";
import Image from "next/image";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import styles from "./page.module.scss";

export default function LoginPage() {
  const router = useRouter(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (loading) return; setLoading(true); setError(""); const response = await fetch("/api/v1/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error?.message || "ورود انجام نشد"); return; } router.push(data.data.mustChangePassword ? "/change-password" : "/dashboard"); router.refresh(); }
  return <main className={styles.page}><section className={styles.loginLayout}><div className={styles.visualPanel}><div className={styles.visualGlow} /><div className={styles.visualContent}><Image src="/assets/icon/OnTyme.png" alt="OnTyme" width={76} height={76} priority className={styles.visualMark} /><Image src="/assets/icon/OnTymeText.png" alt="OnTyme" width={210} height={52} priority className={styles.visualWordmark} /><p>شفافیت در هر روز کاری</p></div><div className={styles.visualFooter}><span /><span>دسترسی امن به فضای کاری</span></div></div><div className={styles.formPanel}><div className={styles.brand}><Image className={styles.mark} src="/assets/icon/OnTyme.png" alt="OnTyme" width={42} height={42} priority /><Image src="/assets/icon/OnTymeText.png" alt="OnTyme" width={132} height={32} priority className={styles.wordmark} /></div><div className={styles.heading}><p className={styles.kicker}>خوش آمدید</p><h1>ورود به آن‌تایم</h1><p>برای ورود به فضای کاری خود، مشخصات حساب را وارد کنید.</p></div><form onSubmit={submit} className={styles.form}><label>نام کاربری<input dir="ltr" value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" placeholder="نام کاربری خود را وارد کنید" required /></label><label>رمز عبور<input dir="ltr" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" placeholder="رمز عبور خود را وارد کنید" required /></label>{error && <div className="alert danger" role="alert">{error}</div>}<button className="button primary wide" disabled={loading}>{loading ? "در حال ورود…" : "ورود به آن‌تایم"}</button></form><div className={styles.note}><span className={styles.noteIcon}>i</span><p>حساب‌ها توسط مدیر سازمان ایجاد و مدیریت می‌شوند.</p></div><p className={styles.copyright}>© {new Date().getFullYear()} OnTyme</p></div></section></main>;
}
