import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/server/auth";
import { db } from "@/server/db";
import { hashPassword, passwordIsStrong } from "@/server/security";
import { audit } from "@/server/audit";
import { employeeScopeWhere } from "@/server/permissions";
const schema=z.object({username:z.string().regex(/^[A-Za-z0-9_.-]+$/),password:z.string().min(10),employeeCode:z.string().min(1).max(30),firstName:z.string().min(1),lastName:z.string().min(1),departmentId:z.string().optional(),teamId:z.string().optional(),role:z.enum(["EMPLOYEE","MANAGER","HR_ADMIN","AUDITOR"]).default("EMPLOYEE")});
export async function GET(){const user=await getCurrentUser();if(!user)return NextResponse.json({error:{code:"UNAUTHENTICATED",message:"نیاز به ورود دارید."}},{status:401});const scope=await employeeScopeWhere(user);const rows=await db.employee.findMany({where:scope,include:{department:true,team:true,manager:true,user:{select:{username:true,role:true,status:true}}},orderBy:{employeeCode:"asc"},take:1000});return NextResponse.json({data:rows});}
export async function POST(request:Request){const user=await getCurrentUser();if(!user||!["ADMIN","HR_ADMIN","MANAGER"].includes(user.role))return NextResponse.json({error:{code:"FORBIDDEN",message:"دسترسی کافی ندارید."}},{status:403});const input=schema.safeParse(await request.json().catch(()=>({})));if(!input.success||!passwordIsStrong(input.data.password))return NextResponse.json({error:{code:"VALIDATION_ERROR",message:"اطلاعات کارمند یا رمز عبور معتبر نیست."}},{status:400});if(user.role==="MANAGER"&&input.data.role!=="EMPLOYEE")return NextResponse.json({error:{code:"FORBIDDEN",message:"مدیر فقط می‌تواند کارمند ایجاد کند."}},{status:403});const scope=await employeeScopeWhere(user);if(user.role==="MANAGER"&&input.data.teamId&&!((scope as {OR?:Array<{teamId?:{in:string[]}}>} ).OR?.some((x)=>x.teamId?.in.includes(input.data.teamId!))))return NextResponse.json({error:{code:"FORBIDDEN",message:"تیم خارج از حوزهٔ مدیریت شماست."}},{status:403});try{const employee=await db.$transaction(async(tx)=>{const createdUser=await tx.user.create({data:{companyId:user.companyId,username:input.data.username,firstName:input.data.firstName,lastName:input.data.lastName,role:input.data.role,passwordHash:await hashPassword(input.data.password),mustChangePassword:true}});return tx.employee.create({data:{companyId:user.companyId,userId:createdUser.id,employeeCode:input.data.employeeCode,firstName:input.data.firstName,lastName:input.data.lastName,departmentId:input.data.departmentId||null,teamId:input.data.teamId||null,employmentStart:new Date(),createdById:user.id}})});await audit({companyId:user.companyId,actorId:user.id,action:"employee.create",entityType:"Employee",entityId:employee.id});return NextResponse.json({data:employee},{status:201});}catch{return NextResponse.json({error:{code:"CONFLICT",message:"نام کاربری یا کد پرسنلی تکراری است."}},{status:409});}}
