import { NextResponse } from "next/server";
import { getCurrentUser } from "@/server/auth";
import { db } from "@/server/db";
import { parseDelimited, parseXlsx, fingerprint } from "@/server/import-engine";
import { EventType } from "@prisma/client";
import { audit } from "@/server/audit";
import { recalculateDates } from "@/server/attendance-service";
export async function GET(){const user=await getCurrentUser();if(!user||!["ADMIN","HR_ADMIN"].includes(user.role))return NextResponse.json({error:{code:"FORBIDDEN",message:"دسترسی کافی ندارید."}},{status:403});return NextResponse.json({data:await db.importJob.findMany({where:{companyId:user.companyId},include:{device:true,errors:true},orderBy:{createdAt:"desc"},take:50})});}
export async function POST(request:Request){const user=await getCurrentUser();if(!user||!["ADMIN","HR_ADMIN"].includes(user.role))return NextResponse.json({error:{code:"FORBIDDEN",message:"دسترسی کافی ندارید."}},{status:403});const form=await request.formData();const file=form.get("file");const deviceId=String(form.get("deviceId")||"");const mapping=JSON.parse(String(form.get("mapping")||'{"externalId":"employeeCode","timestamp":"timestamp","type":"type"}')) as {externalId:string;timestamp:string;type?:string};if(!(file instanceof File)||!deviceId)return NextResponse.json({error:{code:"VALIDATION_ERROR",message:"فایل و دستگاه را انتخاب کنید."}},{status:400});if(file.size>Number(process.env.MAX_IMPORT_BYTES||10485760))return NextResponse.json({error:{code:"FILE_TOO_LARGE",message:"حجم فایل بیش از حد مجاز است."}},{status:413});const buffer=Buffer.from(await file.arrayBuffer());const rows=file.name.toLowerCase().endsWith(".xlsx")||file.name.toLowerCase().endsWith(".xls")?parseXlsx(buffer,mapping):parseDelimited(buffer.toString("utf8"),mapping);const device=await db.attendanceDevice.findFirst({where:{id:deviceId,companyId:user.companyId}});if(!device)return NextResponse.json({error:{code:"NOT_FOUND",message:"دستگاه معتبر نیست."}},{status:404});const job=await db.$transaction(async(tx)=>{const created=await tx.importJob.create({data:{companyId:user.companyId,deviceId,createdById:user.id,filename:file.name.replace(/[^\w.\u0600-\u06ff-]/g,"_"),adapterId:file.name.endsWith(".xlsx")?"generic-xlsx":"canonical-csv",status:"VALIDATING",rowCount:rows.length}});let imported=0,duplicates=0;for(const row of rows){const fp=fingerprint(deviceId,row);const employee=await tx.employee.findFirst({where:{companyId:user.companyId,OR:[{employeeCode:row.externalId},{deviceMappings:{some:{deviceId,externalId:row.externalId}}}]}});try{await tx.rawAttendanceEvent.create({data:{companyId:user.companyId,deviceId,importJobId:created.id,employeeId:employee?.id,externalId:row.externalId,timestamp:row.timestamp,type:row.type as EventType,fingerprint:fp,sourceRow:row.sourceRow,sourceData:row.raw as any}});imported++;}catch{duplicates++;}}return tx.importJob.update({where:{id:created.id},data:{status:"COMPLETED",importedCount:imported,duplicateCount:duplicates,errorCount:rows.length-imported}})});const affected=await db.rawAttendanceEvent.findMany({where:{importJobId:job.id,employeeId:{not:null}},select:{employeeId:true,timestamp:true}});await recalculateDates(user.companyId,Array.from(new Set(affected.map(x=>x.employeeId!).filter(Boolean))),Array.from(new Map(affected.map(x=>{const d=new Date(x.timestamp);d.setUTCHours(0,0,0,0);return [d.toISOString(),d]})).values()));await audit({companyId:user.companyId,actorId:user.id,action:"attendance.import",entityType:"ImportJob",entityId:job.id,after:{imported:job.importedCount,duplicates:job.duplicateCount}});return NextResponse.json({data:job},{status:201});}


