ALTER TABLE "Holiday" ADD COLUMN "calendarYear" INTEGER;
ALTER TABLE "Holiday" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Holiday" ADD COLUMN "sourceReference" TEXT;
ALTER TABLE "Holiday" ADD COLUMN "isOfficial" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Holiday" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;
