"use client";

import { useEffect, useState } from "react";

export default function SelfAttendanceSettingsPage() {
  const [settings, setSettings] = useState({ enabled: false, latitude: "", longitude: "", radiusMeters: "250" });
  const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/v1/self-attendance/settings").then((response) => response.json()).then((result) => { if (result.data) setSettings({ enabled: result.data.enabled, latitude: result.data.latitude === null ? "" : String(result.data.latitude), longitude: result.data.longitude === null ? "" : String(result.data.longitude), radiusMeters: String(result.data.radiusMeters) }); }); }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const input = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/v1/self-attendance/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: input.enabled === "on", latitude: input.latitude ? Number(input.latitude) : null, longitude: input.longitude ? Number(input.longitude) : null, radiusMeters: Number(input.radiusMeters) }) }); const result = await response.json(); setMessage(response.ok ? "تنظیمات محدوده مکانی ذخیره شد." : result.error?.message || "ذخیره تنظیمات ناموفق بود."); }
  return <><div className="sectionTitle"><div><p className="eyebrow">حضور خوداظهاری</p><h1>کنترل موقعیت مکانی</h1><p>در صورت نیاز، حضور و خروج کارکنان را به محدوده مکانی مشخص‌شده محدود کنید.</p></div></div><section className="card"><form className="stack" onSubmit={submit}><label><input name="enabled" type="checkbox" checked={settings.enabled} onChange={(event) => setSettings({ ...settings, enabled: event.target.checked })} /> فعال‌سازی محدوده مکانی</label><div className="two"><label>عرض جغرافیایی<input name="latitude" type="number" step="any" value={settings.latitude} onChange={(event) => setSettings({ ...settings, latitude: event.target.value })} /></label><label>طول جغرافیایی<input name="longitude" type="number" step="any" value={settings.longitude} onChange={(event) => setSettings({ ...settings, longitude: event.target.value })} /></label></div><label>شعاع به متر<input name="radiusMeters" type="number" min="25" max="10000" value={settings.radiusMeters} onChange={(event) => setSettings({ ...settings, radiusMeters: event.target.value })} /></label>{message && <div className="alert success">{message}</div>}<button className="button primary">ذخیره کنترل موقعیت</button></form></section></>;
}
